### ISSUE TITLE
Game Plan

### ISSUE THREAD

**Issue by enilsen16** [enilsen16/urban_pass#1]
http://stackoverflow.com/questions/7621341/how-can-i-programmatically-generate-heroku-like-subdomain-names

We need a way to bring in a users dictionary file. I am thinking we could create a array with the word count of a users dictionary file. Since the user is expected to store the word elsewhere. The order should not matter. Also I think we should copy the words to the users clipboard.

Here are a few examples we can look at:
- https://github.com/pezra/random-word/tree/master/lib/random_word
- https://github.com/javierjulio/dictionary

Could using Faker be an option?

Also we can use this https://github.com/janlelis/clipboard, to copy the output directly to clipboard. That way a user can directly paste it. :smile: 
### Generator(Here's what I am thinking)
- User runs word_picker with the number of characters they want(no spaces, dashes, etc...)

```
Usage: word_picker 4
correcthorsebatterystaple
```
- Word_picker uses random integers (use [`SecureRandom`](http://ruby-doc.org/stdlib-2.1.4/libdoc/securerandom/rdoc/SecureRandom.html) instead of `rand`) to choose words from a users dictionary(or a provided dictonary file)
- ~~Checks the characters to make sure that it matches the original desired length~~
- ~~If not, it repeats(for now Im sure theres a better way though :confused: )~~
- Instead of that lets just let the user specify how many random words they want, as well as print the length of that string
  - Maybe even have a yes or no question asking if they want to use that phrase(incase its to long for the given field)
-  Once it does meet the required length, then it copy that to clipboard and prints it to stdout

![Imgur](http://i.imgur.com/T9PApGP.png)

Thoughts @Marco-Lindsay?

**Comment by sunny-mittal** [comment]
Here's an idea...maybe...pick a word at random from the user's dictionary, Google it, and then choose `x` words from the search results.
